/* Strings for the contact chat (EN / HU). */
export const CHAT_COPY = {
  en: {
    today: 'Today',
    reply: 'Usually replies in ~1h',
    chatHi: "Hi, I'm Martin.",
    chatQ: 'How can I help?',
    chatOpts: ["I'd like a Shopify store", 'UX polish on an existing site', 'Other'],
    freeReply: 'Got it, thank you.',
    ready: 'All set. Your email will be ready to send with these details.',
    readyHi: 'Say hello by email whenever you like.',
    noted: 'Added to your message.',
    subjFree: 'Hi Martin',
    hiLine: 'Hi Martin,',
    bye: 'Best,',
    introShop: "I'd like to talk about building a Shopify store.",
    introUx: 'I have a site that could use some UX polish.',
    introOther: 'I have a project idea that does not fit the usual boxes.',
    chatSubj: ['Shopify store project', 'UX polish for my site', 'A project idea'],
    back: 'Back one step',
    chatAgain: 'Start over',
    confirmReset: 'Sure? Tap again',
    dateAria: 'Pick a start date',
    cantHelp: "Unfortunately, I can't help with this one.",
    limitMsg: 'That is the limit for notes. Add the rest in the email.',
    next: 'Next →',
    ph0: 'Write a message…',
    phAns: 'Type your answer…',
    phEnd: 'Go back a step or start over',
    phLock: 'Choose one of the options above',
    phNote: 'Add a note to the email…',
    phName: 'Your name',
    phSite: 'e.g. myshop.com',
    phAbout: 'Write a short paragraph…',
    phPlat: 'e.g. Magento, PrestaShop',
    phLang: 'e.g. Hungarian, German, Polish',
    phMkt: 'e.g. Hungary, Austria, Poland',
    phProd: 'e.g. 40',
    send: 'Send message',
    sentLink: 'write to me directly',
    sentPost: '.',
    sentPre: 'Did your email app open? If not, ',
    prevSubj: 'Subject',
    prevTitle: 'Your email (preview)',
    privacy: 'Nothing is sent from this page. You send the email yourself.',
    lbAbout: 'About the project',
    lbNote: 'Message',
    lbName: 'Name',
    lbExist: 'Existing store',
    lbPlat: 'Platform',
    lbBrand: 'Brand & products',
    lbLang: 'Languages',
    lbMkt: 'Markets',
    lbProd: 'Number of products',
    lbInteg: 'Integrations',
    lbSite: 'My site',
    lbProb: 'Main problems',
    lbIdea: 'The idea',
    lbKind: 'Kind of help',
    lbTime: 'Timing',
    qName: 'What should I call you?',
    qExist: 'Do you already have an online store?',
    qPlat: 'Which platform is it on?',
    qBrand: 'Do you already have a brand and products?',
    qLang: 'Which languages should the store speak? Pick one, or type your own.',
    qMkt: 'Where would you like to sell?',
    qProd: 'How many products will the store have? Please type a number.',
    qInteg: 'What should the store connect to? Pick any, then tap Next.',
    qAbout:
      'Tell me about the project in a short paragraph: what you sell, who it is for, and what matters most to you.',
    qSite: "What is your site's address?",
    qProb: 'What bothers you most about the site? Pick any, then tap Next.',
    qIdea: 'Tell me a bit about the idea.',
    qKind: 'What kind of help are you after? Pick any, then tap Next.',
    qTime: 'When would you like to start?',
    ansName: ['Skip'],
    ansExist: ['No, this is my first', 'Yes, on another platform', 'Yes, already on Shopify'],
    ansPlat: ['WooCommerce', 'Shoprenter', 'UNAS', 'Wix', 'Other…'],
    ansUxPlat: ['Shopify', 'WooCommerce', 'Shoprenter', 'UNAS', 'Wix', 'Other'],
    ansBrand: ['Yes', 'Still figuring it out'],
    ansLang: ['Hungarian + English', 'Hungarian only', 'English only', 'Other languages…'],
    ansMkt: ['Only Hungary', 'Hungary + EU markets', 'Worldwide', 'Other countries…'],
    ansProd: ['Not sure yet'],
    ansInteg: [
      'Online payments',
      'Invoicing',
      'Shipping / pickup points',
      'Custom features (quiz, gift finder…)',
      'B2B ordering',
      'Not sure yet'
    ],
    ansAbout: ["I'd rather talk it through in an online meeting"],
    ansSite: [],
    ansProb: ['Mobile experience', 'Checkout', 'Speed', 'Design / branding', 'Conversion', 'Navigation'],
    ansIdea: ["I'll explain in the email"],
    ansKind: ['Custom development', 'B2B / wholesale ordering', 'Migration', 'Audit / consulting', 'Other'],
    ansTime: ['As soon as possible', 'In 1–2 months', 'Pick a date…'],
    prodHint: 'A number is enough, for example 40.',
    aboutHint:
      'A few more words, please (at least 15 characters), or tap the button to talk it through in an online meeting.',
    timeHint: "Please keep it short, for example 'in March', or pick a date.",
    siteHint: 'Please enter the address, for example myshop.com.',
    greetName: (name) => `Nice to meet you, ${name}!`
  },
  hu: {
    today: 'Ma',
    reply: 'Általában 1 órán belül válaszolok',
    chatHi: 'Szia, Martin vagyok.',
    chatQ: 'Miben segíthetek?',
    chatOpts: ['Shopify boltot szeretnék', 'UX finomhangolás egy meglévő oldalon', 'Egyéb'],
    freeReply: 'Értem, köszönöm.',
    ready: 'Kész. A levél ezekkel az adatokkal indulhat.',
    readyHi: 'Köszönj emailben, amikor csak kedved tartja.',
    noted: 'Hozzáadtam az üzenetedhez.',
    subjFree: 'Szia Martin',
    hiLine: 'Szia Martin!',
    bye: 'Üdvözlettel,',
    introShop: 'Szeretnék beszélni egy Shopify bolt építéséről.',
    introUx: 'Van egy oldalam, ami ráférne egy kis UX finomhangolás.',
    introOther: 'Van egy projektötletem, ami nem fér bele a szokásos keretekbe.',
    chatSubj: ['Shopify bolt projekt', 'UX finomhangolás az oldalamra', 'Egy projektötlet'],
    back: 'Vissza egy lépést',
    chatAgain: 'Újrakezdés',
    confirmReset: 'Biztos? Koppints újra',
    dateAria: 'Válaszd ki a kezdési dátumot',
    cantHelp: 'Sajnos ebben nem tudok segíteni.',
    limitMsg: 'Ennyi fér a megjegyzésbe. A többit írd meg a levélben.',
    next: 'Tovább →',
    ph0: 'Írj üzenetet…',
    phAns: 'Írd be a válaszod…',
    phEnd: 'Lépj vissza, vagy kezdd újra',
    phLock: 'Válassz a fenti lehetőségek közül',
    phNote: 'Fűzz megjegyzést a levélhez…',
    phName: 'A neved',
    phSite: 'pl. webshopom.hu',
    phAbout: 'Írj egy rövid bekezdést…',
    phPlat: 'pl. Magento, PrestaShop',
    phLang: 'pl. magyar, német, lengyel',
    phMkt: 'pl. Magyarország, Ausztria, Lengyelország',
    phProd: 'pl. 40',
    send: 'Írj üzenetet',
    sentLink: 'írj nekem közvetlenül',
    sentPost: '.',
    sentPre: 'Megnyílt a levelezőprogramod? Ha nem, ',
    prevSubj: 'Tárgy',
    prevTitle: 'A leveled (előnézet)',
    privacy: 'Az oldal nem küld el semmit. A levelet te küldöd el.',
    lbAbout: 'A projektről',
    lbNote: 'Üzenet',
    lbName: 'Név',
    lbExist: 'Meglévő bolt',
    lbPlat: 'Rendszer',
    lbBrand: 'Márka és termékek',
    lbLang: 'Nyelvek',
    lbMkt: 'Piacok',
    lbProd: 'Termékek száma',
    lbInteg: 'Integrációk',
    lbSite: 'Az oldalam',
    lbProb: 'Fő problémák',
    lbIdea: 'Az ötlet',
    lbKind: 'Segítség típusa',
    lbTime: 'Időzítés',
    qName: 'Hogyan szólíthatlak?',
    qExist: 'Van már webshopod?',
    qPlat: 'Melyik rendszeren fut?',
    qBrand: 'Van már márkád és termékeid?',
    qLang: 'Milyen nyelveken legyen elérhető a bolt? Válassz, vagy írd be a sajátodat.',
    qMkt: 'Hol szeretnél eladni?',
    qProd: 'Hány termék lesz a boltban? Kérlek, számmal írd be.',
    qInteg: 'Mihez kapcsolódjon a bolt? Válassz bármennyit, aztán Tovább.',
    qAbout: 'Mesélj a projektről pár mondatban: mit árulsz, kinek, és mi a legfontosabb számodra.',
    qSite: 'Mi az oldalad címe?',
    qProb: 'Mi zavar a legjobban az oldalon? Válassz bármennyit, aztán Tovább.',
    qIdea: 'Mesélj egy kicsit az ötletről.',
    qKind: 'Miben kérsz segítséget? Válassz bármennyit, aztán Tovább.',
    qTime: 'Mikor kezdenéd?',
    ansName: ['Kihagyom'],
    ansExist: ['Nincs, ez lesz az első', 'Van, másik rendszeren', 'Van, már Shopify-on'],
    ansPlat: ['WooCommerce', 'Shoprenter', 'UNAS', 'Wix', 'Más…'],
    ansUxPlat: ['Shopify', 'WooCommerce', 'Shoprenter', 'UNAS', 'Wix', 'Más'],
    ansBrand: ['Igen', 'Még alakul'],
    ansLang: ['Magyar + angol', 'Csak magyar', 'Csak angol', 'Más nyelvek…'],
    ansMkt: ['Csak Magyarországon', 'Magyarország + EU piacok', 'Világszerte', 'Más országok…'],
    ansProd: ['Még nem tudom'],
    ansInteg: [
      'Online fizetés',
      'Számlázás',
      'Szállítás / csomagpont',
      'Egyedi funkciók (kvíz, ajándékválasztó…)',
      'B2B rendelés',
      'Még nem tudom'
    ],
    ansAbout: ['Inkább beszéljük meg online meet-en'],
    ansSite: [],
    ansProb: [
      'Mobilos élmény',
      'Fizetés / checkout',
      'Sebesség',
      'Arculat / design',
      'Konverzió',
      'Navigáció'
    ],
    ansIdea: ['Majd leírom a levélben'],
    ansKind: [
      'Egyedi fejlesztés',
      'B2B / nagykereskedelmi rendelés',
      'Migráció',
      'Átvilágítás / tanácsadás',
      'Egyéb'
    ],
    ansTime: ['Minél hamarabb', '1–2 hónapon belül', 'Dátum választása…'],
    prodHint: 'Elég egy szám, például 40.',
    aboutHint:
      'Írj egy kicsit többet (legalább 15 karakter), vagy koppints a gombra, és online meet-en megbeszéljük.',
    timeHint: "Kérlek, röviden írd le, például 'márciusban', vagy válassz dátumot.",
    siteHint: 'Kérlek, add meg a címet, például webshopom.hu.',
    greetName: (name) => `Szia, ${name}! Örülök, hogy írtál.`
  }
}
